"""empty message

Revision ID: ec57e90905e9
Revises: 5a2b3edc75e8
Create Date: 2022-10-09 23:05:09.162060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec57e90905e9'
down_revision = '5a2b3edc75e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('image', sa.String(length=500), nullable=True))
    op.add_column('Artist', sa.Column('facebook', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('site', sa.String(length=500), nullable=True))
    op.drop_column('Artist', 'image_link')
    op.drop_column('Artist', 'facebook_link')
    op.add_column('Venue', sa.Column('image', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('facebook', sa.String(length=120), nullable=True))
    op.drop_column('Venue', 'image_link')
    op.drop_column('Venue', 'facebook_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'facebook')
    op.drop_column('Venue', 'image')
    op.add_column('Artist', sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'site')
    op.drop_column('Artist', 'facebook')
    op.drop_column('Artist', 'image')
    # ### end Alembic commands ###
